// boxer plugin for OpenCode. Generated by `boxer package opencode` dev; regenerate rather than edit.
//
// Every decision is made by the `boxer hook opencode` binary so this file carries no policy: it
// forwards the shell tool's command and applies the answer (rewrite, deny, or nothing).
import type { Plugin } from "@opencode-ai/plugin";

type Answer = { command?: string; deny?: string };

async function ask(payload: Record<string, unknown>): Promise<Answer> {
  const proc = Bun.spawn(["boxer", "hook", "opencode"], {
    stdin: new Blob([JSON.stringify(payload)]),
    stdout: "pipe",
    stderr: "pipe",
  });
  const [out, err] = await Promise.all([new Response(proc.stdout).text(), new Response(proc.stderr).text()]);
  await proc.exited;
  if (err.trim()) console.error(err.trim());
  const line = out.trim();
  return line ? (JSON.parse(line) as Answer) : {};
}

export const BoxerPlugin: Plugin = async ({ directory }) => {
  return {
    event: async ({ event }) => {
      if (event.type === "session.created") {
        await ask({ hook_event_name: "session.created", cwd: directory, session_id: event.properties?.info?.id });
      }
    },
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "bash") return;
      const answer = await ask({
        hook_event_name: "tool.execute.before",
        tool_name: "bash",
        tool_input: { command: output.args.command },
        cwd: output.args.workdir ?? directory,
        session_id: input.sessionID,
      });
      if (answer.deny) throw new Error(answer.deny);
      if (answer.command) output.args.command = answer.command;
    },
  };
};
