#!/usr/bin/env python3
"""Render bench/results.jsonl into the Markdown that gets committed.

Kept separate from bench.sh so a result set can be re-rendered without re-running an hour of
VM work, and so the table in RESULTS.md is provably a function of the JSONL beside it.
"""
import json
import sys
from collections import defaultdict

rows = [json.loads(l) for l in open(sys.argv[1]) if l.strip()]
host = next((r["info"] for r in rows if r["kind"] == "host"), {})
cells = defaultdict(dict)  # kind -> (workload, contender) -> stats
for r in rows:
    if r["kind"] != "host":
        cells[r["kind"]][(r["workload"], r["contender"])] = r["stats"]

NAMES = {
    "host": "host (none)", "seatbelt": "seatbelt", "codex": "codex sandbox",
    "docker_run": "docker run", "docker": "docker exec", "smolvm": "smolvm", "boxer": "boxer",
}
WORKLOADS = [
    ("noop", "`true` — dispatch only"),
    ("stat", "`ls` one directory"),
    ("read", "`grep -rl` over 400 files"),
    ("write", "create and delete 200 files"),
    ("cpu", "50k-iteration shell loop"),
]


def order(kind):
    seen = []
    for (_, c) in cells[kind]:
        if c not in seen:
            seen.append(c)
    return [c for c in NAMES if c in seen]


def table(kind, workloads, label):
    cs = order(kind)
    if not cs:
        return []
    out = ["| " + label + " | " + " | ".join(NAMES.get(c, c) for c in cs) + " |",
           "| --- |" + " ---: |" * len(cs)]
    for w, desc in workloads:
        if not any((w, c) in cells[kind] for c in cs):
            continue
        cols = []
        for c in cs:
            s = cells[kind].get((w, c))
            if not s:
                cols.append("—")
            elif s.get("failures"):
                # The command failed, so the timing is an error path, not a measurement.
                cols.append("**err**")
            else:
                cols.append(f"{s['p50']:.0f}" + (f" ({s['p90']:.0f})" if s["p90"] > s["p50"] * 1.25 else ""))
        out.append(f"| {desc} | " + " | ".join(cols) + " |")
    return out


def overhead():
    """boxer vs the two denominators that matter: no sandbox at all, and the platform alone."""
    out = ["| workload | vs host (no sandbox) | vs raw smolvm | vs docker exec |", "| --- | ---: | ---: | ---: |"]
    for w, desc in WORKLOADS:
        b = cells["warm"].get((w, "boxer"))
        if not b:
            continue
        cols = []
        for base in ("host", "smolvm", "docker"):
            s = cells["warm"].get((w, base))
            if not s or s.get("failures") or b.get("failures"):
                cols.append("—")
            elif s["p50"] <= 0:
                cols.append("—")
            else:
                d = b["p50"] - s["p50"]
                cols.append(f"{b['p50']/s['p50']:.2f}× ({d:+.0f} ms)")
        out.append(f"| {desc} | " + " | ".join(cols) + " |")
    return out


print(f"""# Benchmark results

Generated by `bench/bench.sh`; rendered from `bench/results.jsonl` by `bench/report.py`.
Read [README.md](README.md) for what each contender is and what these numbers do and do not
mean — in particular, that the process-level sandboxes are not isolating the same thing boxer is.

**Host**

| | |
| --- | --- |
| CPU | {host.get('cpu', '?')} ({host.get('cores', '?')} cores) |
| OS | {host.get('os', '?')} |
| boxer | {host.get('boxer', '?')} |
| smolvm | {host.get('smolvm', '?')} |
| Docker | {host.get('docker', '?')} |
| Codex | {host.get('codex', '?')} |

## Warm command latency

Milliseconds, median of the samples, p90 in parentheses when it is more than 25% above the
median. Lower is better. Every contender ran the same shell line over the same corpus.

{chr(10).join(table('warm', WORKLOADS, 'workload'))}

## What boxer costs

{chr(10).join(overhead())}

## Cold start

One sample: the first command in a sandbox that does not exist yet. `docker run` pays this on
every command by construction, which is why its warm row and its cold row are the same number.

{chr(10).join(table('cold', [('noop', 'first command')], 'first command'))}

## boxer interception paths

Not a comparison — no other contender has these. They are on the critical path of every agent
tool call boxer rewrites, so a regression here is felt everywhere and shows up nowhere else.

{chr(10).join(table('path', [(k, '`' + k + '`') for k in ('hook-rewrite', 'brief', 'status')], 'path'))}
""")
