// boxer plugin for OpenCode. Generated by `boxer package opencode` [[.Version]]; regenerate rather than edit.
//
// Every decision is made by the `boxer hook opencode` binary so this file carries no policy: it
// forwards the shell tool's command and applies the answer (rewrite, deny, or nothing).
import type { Plugin } from "@opencode-ai/plugin";

type Answer = { command?: string; deny?: string };

async function ask(payload: Record<string, unknown>): Promise<Answer> {
  const proc = Bun.spawn(["boxer", "hook", "opencode"], {
    stdin: new Blob([JSON.stringify(payload)]),
    stdout: "pipe",
    stderr: "pipe",
  });
  const [out, err] = await Promise.all([new Response(proc.stdout).text(), new Response(proc.stderr).text()]);
  const code = await proc.exited;
  if (err.trim()) console.error(err.trim());
  const line = out.trim();
  // Fail closed: a boxer that crashed or answered with nothing it can read must not let the
  // command through. A missing binary already throws from Bun.spawn, which aborts the tool.
  if (!line) {
    return code === 0 ? {} : { deny: `boxer hook opencode exited ${code} without an answer; the command was not run` };
  }
  try {
    return JSON.parse(line) as Answer;
  } catch {
    return { deny: "boxer hook opencode gave an unreadable answer; the command was not run" };
  }
}

export const BoxerPlugin: Plugin = async ({ directory }) => {
  return {
    event: async ({ event }) => {
      if (event.type === "session.created") {
        await ask({ hook_event_name: "session.created", cwd: directory, session_id: event.properties?.info?.id });
      }
    },
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "bash") return;
      const answer = await ask({
        hook_event_name: "tool.execute.before",
        tool_name: "bash",
        tool_input: { command: output.args.command },
        cwd: output.args.workdir ?? directory,
        session_id: input.sessionID,
      });
      if (answer.deny) throw new Error(answer.deny);
      if (answer.command) output.args.command = answer.command;
    },
  };
};
