// boxer extension for pi. Generated by `boxer package pi` dev; regenerate rather than edit.
//
// Every decision is made by the `boxer hook pi` binary; this file forwards the bash tool's command
// and applies the answer (rewrite, block, or nothing), injects the brief at session start, and
// registers boxer_run as an explicit tool.
import { spawn } from "node:child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "@sinclair/typebox";

type Answer = { command?: string; deny?: string; context?: string };

function ask(payload: Record<string, unknown>): Promise<Answer> {
  return new Promise((resolve) => {
    const proc = spawn("boxer", ["hook", "pi"], { stdio: ["pipe", "pipe", "inherit"] });
    let out = "";
    proc.stdout.on("data", (d) => (out += d.toString()));
    proc.on("close", () => {
      const line = out.trim();
      resolve(line ? (JSON.parse(line) as Answer) : {});
    });
    proc.on("error", () => resolve({}));
    proc.stdin.end(JSON.stringify(payload));
  });
}

function run(args: string[], cwd: string): Promise<{ code: number; out: string }> {
  return new Promise((resolve) => {
    const proc = spawn("boxer", args, { cwd, stdio: ["ignore", "pipe", "pipe"] });
    let out = "";
    proc.stdout.on("data", (d) => (out += d.toString()));
    proc.stderr.on("data", (d) => (out += d.toString()));
    proc.on("close", (code) => resolve({ code: code ?? 1, out }));
  });
}

export default function (pi: ExtensionAPI) {
  pi.on("session_start", async (_event, ctx) => {
    const a = await ask({ hook_event_name: "session_start", cwd: ctx.cwd, session_id: ctx.sessionManager?.getSessionId?.() });
    if (a.context) pi.sendMessage({ customType: "boxer", content: a.context, display: false }, { triggerTurn: false });
  });

  pi.on("tool_call", async (event, ctx) => {
    if (event.toolName !== "bash") return;
    const input = event.input as { command: string };
    const a = await ask({
      hook_event_name: "tool_call",
      tool_name: "bash",
      tool_input: { command: input.command },
      cwd: ctx.cwd,
      session_id: ctx.sessionManager?.getSessionId?.(),
    });
    if (a.deny) return { block: true, reason: a.deny };
    if (a.command) input.command = a.command;
  });

  pi.registerTool({
    name: "boxer_run",
    label: "boxer run",
    description: "Run a shell command inside this repository's boxer sandbox (a microVM with the worktree mounted). Returns stdout, stderr, and the exit code.",
    parameters: Type.Object({
      command: Type.String({ description: "POSIX shell command line, executed with sh -c" }),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      const r = await run(["run", "-c", params.command], ctx.cwd);
      return { content: [{ type: "text", text: `${r.out.trimEnd()}\n[exit ${r.code}]` }], details: { exitCode: r.code } };
    },
  });
}
